// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFl8fHXUVov06wjVT6HTdt63GCZLVX0P0',
    appId: '1:161038174483:web:7c8026cb0f42e9643632e6',
    messagingSenderId: '161038174483',
    projectId: 'watch-nest-27170',
    authDomain: 'watch-nest-27170.firebaseapp.com',
    databaseURL: 'https://watch-nest-27170-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watch-nest-27170.firebasestorage.app',
    measurementId: 'G-V0EGWY5GFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxafYkQhPhH-D1mMgsL8z5VhrAvyJSxL4',
    appId: '1:161038174483:android:04fefebeef0bf8603632e6',
    messagingSenderId: '161038174483',
    projectId: 'watch-nest-27170',
    databaseURL: 'https://watch-nest-27170-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watch-nest-27170.firebasestorage.app',
  );
}
